# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hannah', '0002_auto_20160908_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='hannah.Artist'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='hannah.Album'),
        ),
    ]
