# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hannah', '0003_auto_20160908_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='hannah.Artist'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(to='hannah.Album'),
        ),
    ]
